### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by perry-mitchell** [appnexus/native-ad-examples#3]
Following the instructions in the readme, on node 10, I get this error:

```
$ npm start

> native-gallery@0.0.0 start /home/perry/Temp/native-ad-examples
> node scripts/main.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/perry/Temp/native-ad-examples/scripts/main.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! native-gallery@0.0.0 start: `node scripts/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the native-gallery@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/perry/.npm/_logs/2019-04-29T10_13_12_560Z-debug.log
```

**Comment by perry-mitchell** [comment]
The dependencies field is not preset so of course handlebars isn't being installed.
